import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ professor, aluno }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Sobre o Sistema</h1>
        Esse sistema foi criado para aprender o basico do framework Next.js
        <hr />
        <div>Professor: {professor}</div>
        <div>Aluno: {aluno}</div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      professor: "Bonieky",
      aluno: "Leonardo",
    },
  };
}
